from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChatWrappedAgentSpec:
    key: str
    template_dir: str
    tool_name: str
    tool_description: str
    display_name: str
    purpose: str
    example_request: str
    aliases: tuple[str, ...] = field(default_factory=tuple)
    security_hints: tuple[str, ...] = field(default_factory=tuple)
    poll_window_seconds: int = 8
    long_running: bool = False


WRAPPED_CHAT_AGENT_SPECS: tuple[ChatWrappedAgentSpec, ...] = (
    ChatWrappedAgentSpec(
        key="crawler",
        template_dir="crawler",
        tool_name="chat_agent_crawler",
        tool_description="Chat-Agent-Crawler",
        display_name="Crawler",
        purpose="Crawl URLs and capture page content or inventories.",
        example_request="Crawl the URL with url='https://example.com' and system_prompt='Extract the important links and page summary'",
        aliases=("crawler", "crawl", "web crawler"),
        security_hints=("crawl", "crawler", "url", "website", "web page", "scrape"),
    ),
    ChatWrappedAgentSpec(
        key="send_email",
        template_dir="emailer",
        tool_name="chat_agent_send_email",
        tool_description="Chat-Agent-Send-Email",
        display_name="Send Email",
        purpose="Run the Emailer template agent from an isolated runtime copy.",
        example_request="Send email with smtp.username='user@example.com', smtp.password='secret', to='ops@example.com', subject='Alert', body='Email from chat tool'",
        aliases=("send_email", "emailer", "email"),
        security_hints=("email", "send email", "smtp", "mail"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="executer",
        template_dir="executer",
        tool_name="chat_agent_executer",
        tool_description="Chat-Agent-Executer",
        display_name="Executer",
        purpose="Execute configured commands or programs in an isolated agent runtime.",
        example_request="Execute with command='git status' and working_directory='E:\\Repo'",
        aliases=("executer", "executor", "execute"),
        security_hints=("execute", "run command", "launch program"),
    ),
    ChatWrappedAgentSpec(
        key="gitter",
        template_dir="gitter",
        tool_name="chat_agent_gitter",
        tool_description="Chat-Agent-Gitter",
        display_name="Gitter",
        purpose="Run git operations through the Gitter template agent.",
        example_request="Run git operation with repo_path='E:\\Repo', operation='status'",
        aliases=("gitter", "git", "gitter"),
        security_hints=("git", "repository", "branch", "commit", "clone", "pull", "push"),
    ),
    ChatWrappedAgentSpec(
        key="sqler",
        template_dir="sqler",
        tool_name="chat_agent_sqler",
        tool_description="Chat-Agent-SQLer",
        display_name="SQLer",
        purpose="Execute SQL operations through the SQLer template agent.",
        example_request="Execute SQL with connection_string='sqlite:///E:/data/app.db' and query='select * from users limit 10'",
        aliases=("sqler", "sql", "database"),
        security_hints=("sql", "database", "query", "select", "insert", "update", "delete from"),
    ),
    ChatWrappedAgentSpec(
        key="ssher",
        template_dir="ssher",
        tool_name="chat_agent_ssher",
        tool_description="Chat-Agent-SSHer",
        display_name="SSHer",
        purpose="Execute SSH commands on remote hosts using the SSHer template agent.",
        example_request="Run SSH command with host='10.0.0.10', username='admin', command='hostname'",
        aliases=("ssher", "ssh", "remote shell"),
        security_hints=("ssh", "remote host", "remote command"),
    ),
    ChatWrappedAgentSpec(
        key="scper",
        template_dir="scper",
        tool_name="chat_agent_scper",
        tool_description="Chat-Agent-SCPer",
        display_name="SCPer",
        purpose="Transfer files via SCP using the SCPer template agent.",
        example_request="Transfer file with host='10.0.0.10', username='admin', local_path='E:\\Temp\\report.txt', remote_path='/tmp/report.txt'",
        aliases=("scper", "scp", "secure copy"),
        security_hints=("scp", "copy file", "transfer file"),
    ),
    ChatWrappedAgentSpec(
        key="pythonxer",
        template_dir="pythonxer",
        tool_name="chat_agent_pythonxer",
        tool_description="Chat-Agent-Pythonxer",
        display_name="Pythonxer",
        purpose="Run inline Python code through the Pythonxer template agent.",
        example_request="Run python with script='print(2 + 2)'",
        aliases=("pythonxer", "python", "run python"),
        security_hints=("python", "run python", "execute python"),
    ),
    ChatWrappedAgentSpec(
        key="dockerer",
        template_dir="dockerer",
        tool_name="chat_agent_dockerer",
        tool_description="Chat-Agent-Dockerer",
        display_name="Dockerer",
        purpose="Run Docker commands through the Dockerer template agent.",
        example_request="Run docker operation with command='docker ps -a'",
        aliases=("dockerer", "docker"),
        security_hints=("docker", "container", "image", "compose"),
    ),
    ChatWrappedAgentSpec(
        key="kuberneter",
        template_dir="kuberneter",
        tool_name="chat_agent_kuberneter",
        tool_description="Chat-Agent-Kuberneter",
        display_name="Kuberneter",
        purpose="Run kubectl operations through the Kuberneter template agent.",
        example_request="Run kubernetes operation with command='kubectl get pods -A'",
        aliases=("kuberneter", "kubernetes", "kubectl", "k8s"),
        security_hints=("kubectl", "kubernetes", "k8s", "pod", "cluster"),
    ),
    ChatWrappedAgentSpec(
        key="jenkinser",
        template_dir="jenkinser",
        tool_name="chat_agent_jenkinser",
        tool_description="Chat-Agent-Jenkinser",
        display_name="Jenkinser",
        purpose="Trigger Jenkins operations through the Jenkinser template agent.",
        example_request="Run jenkins operation with jenkins_url='http://localhost:8080', job_name='build-app'",
        aliases=("jenkinser", "jenkins"),
        security_hints=("jenkins", "job", "pipeline", "build server"),
    ),
    ChatWrappedAgentSpec(
        key="mongoxer",
        template_dir="mongoxer",
        tool_name="chat_agent_mongoxer",
        tool_description="Chat-Agent-Mongoxer",
        display_name="Mongoxer",
        purpose="Execute MongoDB operations through the Mongoxer template agent.",
        example_request="Run MongoDB operation with mongodb.connection_string='mongodb://localhost:27017/' and mongodb.operation='db.users.find().limit(5)'",
        aliases=("mongoxer", "mongo", "mongodb"),
        security_hints=("mongo", "mongodb", "collection", "document db"),
    ),
    ChatWrappedAgentSpec(
        key="file_creator",
        template_dir="file_creator",
        tool_name="chat_agent_file_creator",
        tool_description="Chat-Agent-File-Creator",
        display_name="File Creator",
        purpose="Create files from the File Creator template agent.",
        example_request="Create a file with filepath='E:\\Temp\\note.txt' and content='Hello from Tlamatini'",
        aliases=("file_creator", "create file"),
        security_hints=("create file", "write file", "save file"),
    ),
    ChatWrappedAgentSpec(
        key="file_extractor",
        template_dir="file_extractor",
        tool_name="chat_agent_file_extractor",
        tool_description="Chat-Agent-File-Extractor",
        display_name="File Extractor",
        purpose="Extract file content using the File Extractor template agent.",
        example_request="Extract file content with path='E:\\Temp\\report.pdf'",
        aliases=("file_extractor", "extract file"),
        security_hints=("extract file", "read document", "parse file"),
    ),
    ChatWrappedAgentSpec(
        key="file_interpreter",
        template_dir="file_interpreter",
        tool_name="chat_agent_file_interpreter",
        tool_description="Chat-Agent-File-Interpreter",
        display_name="File Interpreter",
        purpose="Interpret files with the File Interpreter template agent.",
        example_request="Interpret file with path='E:\\Temp\\report.pdf' and system_prompt='Summarize the key risks and actions'",
        aliases=("file_interpreter", "interpret file", "analyze file"),
        security_hints=("interpret file", "analyze document", "summarize file"),
    ),
    ChatWrappedAgentSpec(
        key="image_interpreter",
        template_dir="image_interpreter",
        tool_name="chat_agent_image_interpreter",
        tool_description="Chat-Agent-Image-Interpreter",
        display_name="Image Interpreter",
        purpose="Analyze images using the Image Interpreter template agent.",
        example_request="Interpret image with images_pathfilenames='E:\\Images\\sample.png' and system_prompt='Describe the scene and OCR any visible text'",
        aliases=("image_interpreter", "interpret image", "analyze image"),
        security_hints=("image", "vision", "screenshot", "photo", "picture"),
    ),
    ChatWrappedAgentSpec(
        key="summarize_text",
        template_dir="summarizer",
        tool_name="chat_agent_summarize_text",
        tool_description="Chat-Agent-Summarize-Text",
        display_name="Summarize Text",
        purpose="Summarize content through the Summarizer template agent.",
        example_request="Summarize text with input_text='Very long text here' and system_prompt='Return a concise executive summary'",
        aliases=("summarize_text", "summarizer", "summarize"),
        security_hints=("summarize", "summary", "condense text"),
    ),
    ChatWrappedAgentSpec(
        key="pser",
        template_dir="pser",
        tool_name="chat_agent_pser",
        tool_description="Chat-Agent-PSer",
        display_name="PSer",
        purpose="Execute PowerShell operations through the PSer template agent.",
        example_request="Run powershell with command='Get-Process | Select-Object -First 5'",
        aliases=("pser", "powershell", "pwsh"),
        security_hints=("powershell", "pwsh", "get-process", "windows command"),
    ),
    ChatWrappedAgentSpec(
        key="notifier",
        template_dir="notifier",
        tool_name="chat_agent_notifier",
        tool_description="Chat-Agent-Notifier",
        display_name="Notifier",
        purpose="Send local desktop or system notifications through the Notifier template agent.",
        example_request="Send a notification with title='Tlamatini' and message='Task finished'",
        aliases=("notifier", "notification", "notify"),
        security_hints=("notification", "notify", "desktop alert"),
    ),
    ChatWrappedAgentSpec(
        key="shoter",
        template_dir="shoter",
        tool_name="chat_agent_shoter",
        tool_description="Chat-Agent-Shoter",
        display_name="Shoter",
        purpose="Take screenshots with the Shoter template agent.",
        example_request="Take a screenshot with output_path='E:\\Temp\\screen.png'",
        aliases=("shoter", "screenshot", "screen capture"),
        security_hints=("screenshot", "screen capture", "take screenshot"),
    ),
    ChatWrappedAgentSpec(
        key="telegramer",
        template_dir="telegramer",
        tool_name="chat_agent_telegramer",
        tool_description="Chat-Agent-Telegramer",
        display_name="Telegramer",
        purpose="Send Telegram messages through the Telegramer template agent.",
        example_request="Send Telegram message with telegram.api_id=123456, telegram.api_hash='hash', telegram.chat_id='Angela-Bennet', telegram.message='Hello from chat'",
        aliases=("telegramer", "telegram"),
        security_hints=("telegram", "telegram message", "send telegram"),
    ),
    ChatWrappedAgentSpec(
        key="whatsapper",
        template_dir="whatsapper",
        tool_name="chat_agent_whatsapper",
        tool_description="Chat-Agent-Whatsapper",
        display_name="Whatsapper",
        purpose="Send WhatsApp messages through the Whatsapper template agent.",
        example_request="Send WhatsApp message with phone_number='+5215555555555' and message='Hello from chat'",
        aliases=("whatsapper", "whatsapp"),
        security_hints=("whatsapp", "send whatsapp", "chat message"),
    ),
    ChatWrappedAgentSpec(
        key="apirer",
        template_dir="apirer",
        tool_name="chat_agent_apirer",
        tool_description="Chat-Agent-Apirer",
        display_name="Apirer",
        purpose="Call HTTP APIs through the Apirer template agent.",
        example_request="Call an API with url='https://httpbin.org/get' and method='GET'",
        aliases=("apirer", "api", "http api"),
        security_hints=("api", "http request", "rest", "endpoint"),
    ),
    ChatWrappedAgentSpec(
        key="prompter",
        template_dir="prompter",
        tool_name="chat_agent_prompter",
        tool_description="Chat-Agent-Prompter",
        display_name="Prompter",
        purpose="Send sub-prompts to another LLM through the Prompter template agent.",
        example_request="Run a sub-prompt with prompt='Explain Kerberos in 5 bullet points'",
        aliases=("prompter", "sub prompt", "llm prompt"),
        security_hints=("prompt another llm", "sub prompt", "llm prompt"),
    ),
    ChatWrappedAgentSpec(
        key="monitor_log",
        template_dir="monitor_log",
        tool_name="chat_agent_monitor_log",
        tool_description="Chat-Agent-Monitor-Log",
        display_name="Monitor Log",
        purpose="Monitor log files continuously through the Monitor Log template agent.",
        example_request="Monitor log with target.logfile_path='E:\\Temp\\app.log' and target.keywords='ERROR,FATAL'",
        aliases=("monitor_log", "log monitor", "monitor log"),
        security_hints=("monitor log", "watch log", "tail log"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="monitor_netstat",
        template_dir="monitor_netstat",
        tool_name="chat_agent_monitor_netstat",
        tool_description="Chat-Agent-Monitor-Netstat",
        display_name="Monitor Netstat",
        purpose="Monitor network connections continuously through the Monitor Netstat template agent.",
        example_request="Monitor netstat with target.port='8080' and target.keywords='ESTABLISHED,LISTENING'",
        aliases=("monitor_netstat", "netstat monitor", "monitor network"),
        security_hints=("netstat", "port status", "monitor network", "listen port"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="kyber_keygen",
        template_dir="kyber_keygen",
        tool_name="chat_agent_kyber_keygen",
        tool_description="Chat-Agent-Kyber-Keygen",
        display_name="Kyber Keygen",
        purpose="Generate Kyber keys through the Kyber Keygen template agent.",
        example_request="Generate Kyber keys with output_directory='E:\\Keys'",
        aliases=("kyber_keygen", "kyber keygen", "key generation"),
        security_hints=("kyber", "keygen", "generate keys", "pqc"),
    ),
    ChatWrappedAgentSpec(
        key="kyber_cipher",
        template_dir="kyber_cipher",
        tool_name="chat_agent_kyber_cipher",
        tool_description="Chat-Agent-Kyber-Cipher",
        display_name="Kyber Cipher",
        purpose="Encrypt data through the Kyber Cipher template agent.",
        example_request="Encrypt data with public_key_path='E:\\Keys\\public.key', input_data='secret text'",
        aliases=("kyber_cipher", "encrypt", "kyber encrypt"),
        security_hints=("encrypt", "encryption", "cipher", "kyber"),
    ),
    ChatWrappedAgentSpec(
        key="kyber_deciph",
        template_dir="kyber_decipher",
        tool_name="chat_agent_kyber_deciph",
        tool_description="Chat-Agent-Kyber-Deciph",
        display_name="Kyber Deciph",
        purpose="Decrypt data through the Kyber Decipher template agent.",
        example_request="Decrypt data with private_key_path='E:\\Keys\\private.key' and ciphertext_path='E:\\Temp\\secret.bin'",
        aliases=("kyber_deciph", "kyber_decipher", "decrypt", "kyber decrypt"),
        security_hints=("decrypt", "decryption", "decipher", "kyber"),
    ),
    ChatWrappedAgentSpec(
        key="move_file",
        template_dir="mover",
        tool_name="chat_agent_move_file",
        tool_description="Chat-Agent-Move-File",
        display_name="Move File",
        purpose="Move or rename files through the Mover template agent.",
        example_request="Move file with source_path='E:\\Temp\\old.txt' and destination_path='E:\\Temp\\new.txt'",
        aliases=("move_file", "mover", "move file", "rename file"),
        security_hints=("move file", "rename file", "relocate file"),
    ),
    ChatWrappedAgentSpec(
        key="deleter",
        template_dir="deleter",
        tool_name="chat_agent_deleter",
        tool_description="Chat-Agent-Deleter",
        display_name="Deleter",
        purpose="Delete files through the Deleter template agent.",
        example_request="Delete file with path='E:\\Temp\\obsolete.txt'",
        aliases=("deleter", "delete file", "remove file"),
        security_hints=("delete file", "remove file", "erase file"),
    ),
    ChatWrappedAgentSpec(
        key="recmailer",
        template_dir="recmailer",
        tool_name="chat_agent_recmailer",
        tool_description="Chat-Agent-Recmailer",
        display_name="Recmailer",
        purpose="Check received emails through the Recmailer template agent.",
        example_request="Check received emails with mail.username='user@example.com' and mail.password='secret'",
        aliases=("recmailer", "receive email", "check mailbox"),
        security_hints=("receive email", "mailbox", "imap", "read email"),
        poll_window_seconds=3,
        long_running=True,
    ),
)


WRAPPED_CHAT_AGENT_MAP = {spec.key: spec for spec in WRAPPED_CHAT_AGENT_SPECS}
WRAPPED_CHAT_AGENT_BY_TOOL_NAME = {spec.tool_name: spec for spec in WRAPPED_CHAT_AGENT_SPECS}
WRAPPED_CHAT_AGENT_BY_DESCRIPTION = {spec.tool_description: spec for spec in WRAPPED_CHAT_AGENT_SPECS}


def get_wrapped_agent_security_hints() -> tuple[str, ...]:
    hints: list[str] = []
    for spec in WRAPPED_CHAT_AGENT_SPECS:
        for hint in spec.security_hints:
            if hint not in hints:
                hints.append(hint)
    return tuple(hints)
