from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChatWrappedAgentSpec:
    key: str
    template_dir: str
    tool_name: str
    tool_description: str
    display_name: str
    purpose: str
    example_request: str
    aliases: tuple[str, ...] = field(default_factory=tuple)
    security_hints: tuple[str, ...] = field(default_factory=tuple)
    poll_window_seconds: int = 8
    long_running: bool = False


WRAPPED_CHAT_AGENT_SPECS: tuple[ChatWrappedAgentSpec, ...] = (
    ChatWrappedAgentSpec(
        key="crawler",
        template_dir="crawler",
        tool_name="chat_agent_crawler",
        tool_description="Chat-Agent-Crawler",
        display_name="Crawler",
        purpose="Crawl any URL and capture its full page content (HTML, scripts, styles, meta tags) or plain text. Supports JavaScript-rendered SPAs. Use when the user asks to scrape, read, or analyze a web page.",
        example_request="Crawl url='https://example.com' with system_prompt='Extract all links, headings, and a page summary' and content_mode='text'",
        aliases=("crawler", "crawl", "web crawler"),
        security_hints=("crawl", "crawler", "url", "website", "web page", "scrape"),
    ),
    ChatWrappedAgentSpec(
        key="send_email",
        template_dir="emailer",
        tool_name="chat_agent_send_email",
        tool_description="Chat-Agent-Send-Email",
        display_name="Send Email",
        purpose="Send an email via SMTP. Use when the user asks to send, compose, or deliver an email message.",
        example_request="Send email with smtp.host='smtp.gmail.com' and smtp.port=587 and smtp.username='user@gmail.com' and smtp.password='APP_PASSWORD' and email.from_address='user@gmail.com' and email.to_addresses='recipient@example.com' and email.subject='Status Report' and pattern='EVENT DETECTED'",
        aliases=("send_email", "emailer", "email"),
        security_hints=("email", "send email", "smtp", "mail"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="executer",
        template_dir="executer",
        tool_name="chat_agent_executer",
        tool_description="Chat-Agent-Executer",
        display_name="Executer",
        purpose="Execute any shell command or program in an isolated subprocess. Use for running scripts, build tools, system commands, or any CLI operation.",
        example_request="Execute with script='npm run build' and non_blocking=false",
        aliases=("executer", "executor", "execute"),
        security_hints=("execute", "run command", "launch program"),
    ),
    ChatWrappedAgentSpec(
        key="gitter",
        template_dir="gitter",
        tool_name="chat_agent_gitter",
        tool_description="Chat-Agent-Gitter",
        display_name="Gitter",
        purpose="Run any git operation (clone, pull, push, commit, status, log, diff, branch, checkout, merge, etc.). Use when the user asks about git repositories.",
        example_request="Run git with repo_path='E:\\Projects\\myapp' and command='log' and branch='main'",
        aliases=("gitter", "git", "gitter"),
        security_hints=("git", "repository", "branch", "commit", "clone", "pull", "push"),
    ),
    ChatWrappedAgentSpec(
        key="sqler",
        template_dir="sqler",
        tool_name="chat_agent_sqler",
        tool_description="Chat-Agent-SQLer",
        display_name="SQLer",
        purpose="Execute SQL queries against any database (SQLite, PostgreSQL, MySQL, SQL Server). Use when the user asks to query, inspect, or modify database data.",
        example_request="Run SQL with sql_connection.server='localhost' and sql_connection.database='mydatabase' and sql_connection.username='sa' and sql_connection.password='PASSWORD' and script='SELECT name, email FROM users WHERE active=1'",
        aliases=("sqler", "sql", "database"),
        security_hints=("sql", "database", "query", "select", "insert", "update", "delete from"),
    ),
    ChatWrappedAgentSpec(
        key="ssher",
        template_dir="ssher",
        tool_name="chat_agent_ssher",
        tool_description="Chat-Agent-SSHer",
        display_name="SSHer",
        purpose="Execute commands on remote hosts via SSH. Use when the user asks to check, configure, or operate a remote server.",
        example_request="SSH with ip='10.0.0.10' and user='admin' and script='df -h && free -m && uptime'",
        aliases=("ssher", "ssh", "remote shell"),
        security_hints=("ssh", "remote host", "remote command"),
    ),
    ChatWrappedAgentSpec(
        key="scper",
        template_dir="scper",
        tool_name="chat_agent_scper",
        tool_description="Chat-Agent-SCPer",
        display_name="SCPer",
        purpose="Transfer files between local machine and remote hosts via SCP (Secure Copy). Use for uploading or downloading files from remote servers.",
        example_request="Copy file with ip='10.0.0.10' and user='admin' and file='E:\\Backups\\db.sql' and direction='send'",
        aliases=("scper", "scp", "secure copy"),
        security_hints=("scp", "copy file", "transfer file"),
    ),
    ChatWrappedAgentSpec(
        key="pythonxer",
        template_dir="pythonxer",
        tool_name="chat_agent_pythonxer",
        tool_description="Chat-Agent-Pythonxer",
        display_name="Pythonxer",
        purpose="Run inline Python code directly. Use when the user needs a quick computation, data transformation, file parsing, or any task best solved with Python code.",
        example_request="Run python with script='import json; data = {\"name\": \"test\", \"value\": 42}; print(json.dumps(data, indent=2))'",
        aliases=("pythonxer", "python", "run python"),
        security_hints=("python", "run python", "execute python"),
    ),
    ChatWrappedAgentSpec(
        key="dockerer",
        template_dir="dockerer",
        tool_name="chat_agent_dockerer",
        tool_description="Chat-Agent-Dockerer",
        display_name="Dockerer",
        purpose="Run any Docker CLI command (ps, images, build, run, stop, logs, compose, etc.). Use when the user asks about containers or Docker operations.",
        example_request="Run docker with command='docker ps -a --format table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
        aliases=("dockerer", "docker"),
        security_hints=("docker", "container", "image", "compose"),
    ),
    ChatWrappedAgentSpec(
        key="kuberneter",
        template_dir="kuberneter",
        tool_name="chat_agent_kuberneter",
        tool_description="Chat-Agent-Kuberneter",
        display_name="Kuberneter",
        purpose="Run any kubectl command against a Kubernetes cluster. Use when the user asks about pods, deployments, services, namespaces, or any K8s resources.",
        example_request="Run kubectl with command='kubectl get pods -n default -o wide'",
        aliases=("kuberneter", "kubernetes", "kubectl", "k8s"),
        security_hints=("kubectl", "kubernetes", "k8s", "pod", "cluster"),
    ),
    ChatWrappedAgentSpec(
        key="jenkinser",
        template_dir="jenkinser",
        tool_name="chat_agent_jenkinser",
        tool_description="Chat-Agent-Jenkinser",
        display_name="Jenkinser",
        purpose="Trigger Jenkins operations through the Jenkinser template agent.",
        example_request="Run jenkins operation with jenkins_url='http://localhost:8080', job_name='build-app'",
        aliases=("jenkinser", "jenkins"),
        security_hints=("jenkins", "job", "pipeline", "build server"),
    ),
    ChatWrappedAgentSpec(
        key="mongoxer",
        template_dir="mongoxer",
        tool_name="chat_agent_mongoxer",
        tool_description="Chat-Agent-Mongoxer",
        display_name="Mongoxer",
        purpose="Execute MongoDB operations through the Mongoxer template agent.",
        example_request="Run MongoDB operation with mongo_connection.connection_string='mongodb://localhost:27017/' and mongo_connection.database='mydatabase' and script='db.users.find().limit(5)'",
        aliases=("mongoxer", "mongo", "mongodb"),
        security_hints=("mongo", "mongodb", "collection", "document db"),
    ),
    ChatWrappedAgentSpec(
        key="file_creator",
        template_dir="file_creator",
        tool_name="chat_agent_file_creator",
        tool_description="Chat-Agent-File-Creator",
        display_name="File Creator",
        purpose="Create or overwrite a file with specified content at any path. Use when the user asks to create, write, or save a file.",
        example_request="Create file with filepath='E:\\Temp\\config.yaml' and content='server:\\n  host: 0.0.0.0\\n  port: 8080'",
        aliases=("file_creator", "create file"),
        security_hints=("create file", "write file", "save file"),
    ),
    ChatWrappedAgentSpec(
        key="file_extractor",
        template_dir="file_extractor",
        tool_name="chat_agent_file_extractor",
        tool_description="Chat-Agent-File-Extractor",
        display_name="File Extractor",
        purpose="Extract readable text from any document (PDF, DOCX, XLSX, TXT, CSV, HTML, etc.). Use when the user asks to read or extract content from a document file.",
        example_request="Extract text with path_filenames='E:\\Documents\\report.pdf'",
        aliases=("file_extractor", "extract file"),
        security_hints=("extract file", "read document", "parse file"),
    ),
    ChatWrappedAgentSpec(
        key="file_interpreter",
        template_dir="file_interpreter",
        tool_name="chat_agent_file_interpreter",
        tool_description="Chat-Agent-File-Interpreter",
        display_name="File Interpreter",
        purpose="Interpret and analyze file contents using an LLM. Use when the user asks to understand, summarize, or analyze a document's meaning rather than just extract its text.",
        example_request="Analyze file with path_filenames='E:\\Docs\\contract.pdf' and reading_type='summarized'",
        aliases=("file_interpreter", "interpret file", "analyze file"),
        security_hints=("interpret file", "analyze document", "summarize file"),
    ),
    ChatWrappedAgentSpec(
        key="image_interpreter",
        template_dir="image_interpreter",
        tool_name="chat_agent_image_interpreter",
        tool_description="Chat-Agent-Image-Interpreter",
        display_name="Image Interpreter",
        purpose="Analyze images using vision AI — describe scenes, OCR text, identify objects, read diagrams, interpret screenshots. Use when the user asks about an image.",
        example_request="Analyze image with images_pathfilenames='E:\\Screenshots\\error.png' and llm.prompt='Describe what you see and transcribe any visible text or error messages'",
        aliases=("image_interpreter", "interpret image", "analyze image"),
        security_hints=("image", "vision", "screenshot", "photo", "picture"),
    ),
    ChatWrappedAgentSpec(
        key="summarize_text",
        template_dir="summarizer",
        tool_name="chat_agent_summarize_text",
        tool_description="Chat-Agent-Summarize-Text",
        display_name="Summarize Text",
        purpose="Summarize long text content using an LLM. Use when the user has a large block of text and wants a concise summary, key points, or executive overview.",
        example_request="Summarize with system_prompt='Return a 5-bullet executive summary focusing on risks and action items'",
        aliases=("summarize_text", "summarizer", "summarize"),
        security_hints=("summarize", "summary", "condense text"),
    ),
    ChatWrappedAgentSpec(
        key="pser",
        template_dir="pser",
        tool_name="chat_agent_pser",
        tool_description="Chat-Agent-PSer",
        display_name="PSer",
        purpose="Find a running process by fuzzy/semantic name (LLM picks the best-matching process from the live process list). Use when the user wants to locate a specific program that may already be running. NOT a PowerShell executor — use chat_agent_executer for shell commands.",
        example_request="Find process with likely_process_name='Paint'",
        aliases=("pser", "process-finder", "find-process"),
        security_hints=("process", "find process", "running process", "pid"),
    ),
    ChatWrappedAgentSpec(
        key="notifier",
        template_dir="notifier",
        tool_name="chat_agent_notifier",
        tool_description="Chat-Agent-Notifier",
        display_name="Notifier",
        purpose="Show a desktop notification with optional sound alert. Use when the user asks to be notified or alerted about something.",
        example_request="Notify with target.search_strings='BUILD DONE' and target.outcome_detail='The build finished successfully' and target.sound_enabled=true",
        aliases=("notifier", "notification", "notify"),
        security_hints=("notification", "notify", "desktop alert"),
    ),
    ChatWrappedAgentSpec(
        key="shoter",
        template_dir="shoter",
        tool_name="chat_agent_shoter",
        tool_description="Chat-Agent-Shoter",
        display_name="Shoter",
        purpose="Take a screenshot of the current screen. Use when the user asks for a screenshot, screen capture, or visual snapshot of what's on screen.",
        example_request="Take screenshot with output_dir='E:\\Screenshots'",
        aliases=("shoter", "screenshot", "screen capture"),
        security_hints=("screenshot", "screen capture", "take screenshot"),
    ),
    ChatWrappedAgentSpec(
        key="telegramer",
        template_dir="telegramer",
        tool_name="chat_agent_telegramer",
        tool_description="Chat-Agent-Telegramer",
        display_name="Telegramer",
        purpose="Send Telegram messages through the Telegramer template agent.",
        example_request="Send Telegram message with telegram.api_id=123456, telegram.api_hash='hash', telegram.chat_id='Angela-Bennet', telegram.message='Hello from chat'",
        aliases=("telegramer", "telegram"),
        security_hints=("telegram", "telegram message", "send telegram"),
    ),
    ChatWrappedAgentSpec(
        key="whatsapper",
        template_dir="whatsapper",
        tool_name="chat_agent_whatsapper",
        tool_description="Chat-Agent-Whatsapper",
        display_name="Whatsapper",
        purpose="Send WhatsApp messages through the Whatsapper template agent.",
        example_request="Send WhatsApp alert with textmebot.phone='+5215555555555' and textmebot.apikey='YOUR_TEXTMEBOT_KEY' and keywords='error, critical' and poll_interval=5",
        aliases=("whatsapper", "whatsapp"),
        security_hints=("whatsapp", "send whatsapp", "chat message"),
    ),
    ChatWrappedAgentSpec(
        key="apirer",
        template_dir="apirer",
        tool_name="chat_agent_apirer",
        tool_description="Chat-Agent-Apirer",
        display_name="Apirer",
        purpose="Call any HTTP REST API endpoint (GET, POST, PUT, DELETE, PATCH). Use when the user asks to call an API, fetch data from a URL, or interact with a web service.",
        example_request="Call API with url='https://api.github.com/repos/anthropics/claude-code' and method='GET' and expected_status=200 and timeout=30",
        aliases=("apirer", "api", "http api"),
        security_hints=("api", "http request", "rest", "endpoint"),
    ),
    ChatWrappedAgentSpec(
        key="prompter",
        template_dir="prompter",
        tool_name="chat_agent_prompter",
        tool_description="Chat-Agent-Prompter",
        display_name="Prompter",
        purpose="Send a prompt to another LLM instance for processing. Use for sub-queries, creative writing, code generation, translation, or any task best delegated to a separate LLM call.",
        example_request="Run prompt with prompt='Explain the CAP theorem in distributed systems with a practical example for each trade-off'",
        aliases=("prompter", "sub prompt", "llm prompt"),
        security_hints=("prompt another llm", "sub prompt", "llm prompt"),
    ),
    ChatWrappedAgentSpec(
        key="monitor_log",
        template_dir="monitor_log",
        tool_name="chat_agent_monitor_log",
        tool_description="Chat-Agent-Monitor-Log",
        display_name="Monitor Log",
        purpose="Monitor log files continuously through the Monitor Log template agent.",
        example_request="Monitor log with target.logfile_path='E:\\Temp\\app.log' and target.keywords='ERROR,FATAL'",
        aliases=("monitor_log", "log monitor", "monitor log"),
        security_hints=("monitor log", "watch log", "tail log"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="monitor_netstat",
        template_dir="monitor_netstat",
        tool_name="chat_agent_monitor_netstat",
        tool_description="Chat-Agent-Monitor-Netstat",
        display_name="Monitor Netstat",
        purpose="Monitor network connections continuously through the Monitor Netstat template agent.",
        example_request="Monitor netstat with target.port='8080' and target.keywords='ESTABLISHED,LISTENING'",
        aliases=("monitor_netstat", "netstat monitor", "monitor network"),
        security_hints=("netstat", "port status", "monitor network", "listen port"),
        poll_window_seconds=3,
        long_running=True,
    ),
    ChatWrappedAgentSpec(
        key="kyber_keygen",
        template_dir="kyber_keygen",
        tool_name="chat_agent_kyber_keygen",
        tool_description="Chat-Agent-Kyber-Keygen",
        display_name="Kyber Keygen",
        purpose="Generate Kyber keys through the Kyber Keygen template agent.",
        example_request="Generate Kyber keys with kyber_variant='kyber-768'",
        aliases=("kyber_keygen", "kyber keygen", "key generation"),
        security_hints=("kyber", "keygen", "generate keys", "pqc"),
    ),
    ChatWrappedAgentSpec(
        key="kyber_cipher",
        template_dir="kyber_cipher",
        tool_name="chat_agent_kyber_cipher",
        tool_description="Chat-Agent-Kyber-Cipher",
        display_name="Kyber Cipher",
        purpose="Encrypt data through the Kyber Cipher template agent.",
        example_request="Encrypt data with kyber_variant='kyber-768' and public_key='<base64-public-key>' and buffer='secret text'",
        aliases=("kyber_cipher", "encrypt", "kyber encrypt"),
        security_hints=("encrypt", "encryption", "cipher", "kyber"),
    ),
    ChatWrappedAgentSpec(
        key="kyber_deciph",
        template_dir="kyber_decipher",
        tool_name="chat_agent_kyber_deciph",
        tool_description="Chat-Agent-Kyber-Deciph",
        display_name="Kyber Deciph",
        purpose="Decrypt data through the Kyber Decipher template agent.",
        example_request="Decrypt data with kyber_variant='kyber-768' and private_key='<base64-private-key>' and encapsulation='<base64-encapsulation>' and initialization_vector='<base64-iv>' and cipher_text='<base64-ciphertext>'",
        aliases=("kyber_deciph", "kyber_decipher", "decrypt", "kyber decrypt"),
        security_hints=("decrypt", "decryption", "decipher", "kyber"),
    ),
    ChatWrappedAgentSpec(
        key="move_file",
        template_dir="mover",
        tool_name="chat_agent_move_file",
        tool_description="Chat-Agent-Move-File",
        display_name="Move File",
        purpose="Move or rename files through the Mover template agent.",
        example_request="Move file with source_files='E:\\Temp\\old.txt' and destination_folder='E:\\Archive' and operation='move' and trigger_mode='immediate'",
        aliases=("move_file", "mover", "move file", "rename file"),
        security_hints=("move file", "rename file", "relocate file"),
    ),
    ChatWrappedAgentSpec(
        key="deleter",
        template_dir="deleter",
        tool_name="chat_agent_deleter",
        tool_description="Chat-Agent-Deleter",
        display_name="Deleter",
        purpose="Delete files through the Deleter template agent.",
        example_request="Delete file with files_to_delete='E:\\Temp\\obsolete.txt' and trigger_mode='immediate'",
        aliases=("deleter", "delete file", "remove file"),
        security_hints=("delete file", "remove file", "erase file"),
    ),
    ChatWrappedAgentSpec(
        key="recmailer",
        template_dir="recmailer",
        tool_name="chat_agent_recmailer",
        tool_description="Chat-Agent-Recmailer",
        display_name="Recmailer",
        purpose="Check received emails through the Recmailer template agent.",
        example_request="Check received emails with imap.host='imap.gmail.com' and imap.port=993 and imap.username='user@example.com' and imap.password='APP_PASSWORD' and keywords_or_phrases='invoice, receipt'",
        aliases=("recmailer", "receive email", "check mailbox"),
        security_hints=("receive email", "mailbox", "imap", "read email"),
        poll_window_seconds=3,
        long_running=True,
    ),
)


WRAPPED_CHAT_AGENT_MAP = {spec.key: spec for spec in WRAPPED_CHAT_AGENT_SPECS}
WRAPPED_CHAT_AGENT_BY_TOOL_NAME = {spec.tool_name: spec for spec in WRAPPED_CHAT_AGENT_SPECS}
WRAPPED_CHAT_AGENT_BY_DESCRIPTION = {spec.tool_description: spec for spec in WRAPPED_CHAT_AGENT_SPECS}


def get_wrapped_agent_security_hints() -> tuple[str, ...]:
    hints: list[str] = []
    for spec in WRAPPED_CHAT_AGENT_SPECS:
        for hint in spec.security_hints:
            if hint not in hints:
                hints.append(hint)
    return tuple(hints)
