"""Version resolution for Tlamatini.

Single source of truth: a git tag of the form ``vMAJOR.MINOR.PATCH`` (SemVer
2.0.0).  Everything else is derived.

Resolution order at runtime (first non-empty wins):

  1. ``agent/_version.py`` — generated by ``build.py`` at build time and
     bundled into the frozen application.  Holds the exact version the
     installer/release was cut against.
  2. ``git describe --tags --long --dirty`` against the working tree —
     covers source-mode developers who haven't run the build script.
  3. ``"0.0.0+unknown"`` — last-resort sentinel so callers never crash.

This module has **no Django dependency** so it is safe to import from
``manage.py`` before Django is initialised, from build scripts, and from
``tlamatini.context_processors``.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional, Tuple


# ── Public constants ────────────────────────────────────────────────────────

UNKNOWN_VERSION = "0.0.0+unknown"

# Strict SemVer 2.0.0 regex.  See https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
_SEMVER_RE = re.compile(
    r"^(?P<major>0|[1-9]\d*)"
    r"\.(?P<minor>0|[1-9]\d*)"
    r"\.(?P<patch>0|[1-9]\d*)"
    r"(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)"
    r"(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(?:\+(?P<build>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
)


# ── Internal helpers ────────────────────────────────────────────────────────

def _read_generated_module() -> Optional[str]:
    """Return ``__version__`` from ``agent._version`` if available."""
    try:
        from agent import _version  # type: ignore[import-not-found]
    except Exception:
        return None
    value = getattr(_version, "__version__", None)
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _repo_root_candidates() -> list[Path]:
    """Possible repository roots, in priority order.

    In source mode the working tree is what we want.  In frozen mode there
    is no git directory, so this returns nothing useful — but the generated
    module path will already have answered, so we never reach here.
    """
    candidates: list[Path] = []
    # 1. Directory containing this file's parent (the Django ``Tlamatini/``
    #    directory) and its parent (the git root).
    here = Path(__file__).resolve()
    candidates.append(here.parent.parent.parent)  # repo root
    candidates.append(here.parent.parent)         # Tlamatini/ Django root
    # 2. CWD — covers running from anywhere inside the tree.
    try:
        candidates.append(Path.cwd())
    except OSError:
        pass
    # Dedup while preserving order.
    seen: set[Path] = set()
    unique: list[Path] = []
    for c in candidates:
        try:
            resolved = c.resolve()
        except OSError:
            continue
        if resolved in seen:
            continue
        seen.add(resolved)
        unique.append(resolved)
    return unique


def _run_git(args: list[str], cwd: Path) -> Optional[str]:
    """Run a git command silently; return stdout stripped or ``None`` on error."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return None
    if result.returncode != 0:
        return None
    out = (result.stdout or "").strip()
    return out or None


def derive_version_from_git(cwd: Optional[Path] = None) -> Optional[str]:
    """Derive a version string from the local git working tree.

    Returns one of:
      * ``"1.2.3"``                              — exact tag match (clean)
      * ``"1.2.3.dev17+gabc1234"``               — N commits past tag v1.2.3
      * ``"1.2.3.dev17+gabc1234.dirty"``         — also has uncommitted edits
      * ``"0.0.0.dev0+gabc1234"``                — no tags at all yet
      * ``"0.0.0.dev0+gabc1234.dirty"``          — no tags AND dirty
      * ``None``                                 — not a git repo / git missing

    The output follows `PEP 440 <https://peps.python.org/pep-0440/>`_ so it
    sorts correctly in installer registries while remaining recognizable to
    a human as SemVer-shaped.
    """
    candidates = [cwd] if cwd is not None else _repo_root_candidates()
    for repo in candidates:
        if repo is None:
            continue
        if not (repo / ".git").exists() and _run_git(["rev-parse", "--git-dir"], repo) is None:
            continue
        # Are there any tags reachable?
        described = _run_git(
            ["describe", "--tags", "--long", "--dirty", "--match", "v[0-9]*"],
            repo,
        )
        commit = _run_git(["rev-parse", "--short=7", "HEAD"], repo) or "unknown"
        dirty = _run_git(["status", "--porcelain"], repo)
        is_dirty = bool(dirty)

        if described:
            # described looks like ``v1.2.3-17-gabc1234`` or
            # ``v1.2.3-17-gabc1234-dirty``.  Strip the leading ``v`` and split.
            stripped = described[1:] if described.startswith("v") else described
            parts = stripped.split("-")
            # Re-join everything before the last 2-3 components in case the
            # tag itself contains a dash (e.g. v1.2.3-rc.1).
            tail_count = 3 if parts[-1] == "dirty" else 2
            tag_body = "-".join(parts[:-tail_count])
            distance = parts[-tail_count]
            sha = parts[-tail_count + 1]
            try:
                n = int(distance)
            except ValueError:
                # describe gave us something unexpected — fall back to tag.
                return tag_body
            if n == 0 and not is_dirty:
                return tag_body
            base = tag_body
            suffix = f".dev{n}+{sha}"
            if is_dirty:
                suffix += ".dirty"
            return f"{base}{suffix}"

        # No tags yet — synthesise a dev version from the commit alone.
        base = f"0.0.0.dev0+g{commit}"
        if is_dirty:
            base += ".dirty"
        return base
    return None


# ── Public API ─────────────────────────────────────────────────────────────

def get_version() -> str:
    """Return the running version string.

    Resolution order: generated module → git describe → ``UNKNOWN_VERSION``.
    Always returns a non-empty string, never raises.
    """
    generated = _read_generated_module()
    if generated:
        return generated
    derived = derive_version_from_git()
    if derived:
        return derived
    return UNKNOWN_VERSION


def get_version_info() -> dict:
    """Return a structured view of the version for the ``/agent/version/`` endpoint.

    Keys:
      * ``version``  — public SemVer string (what users see)
      * ``build``    — full descriptor including local part / dirty flag
      * ``commit``   — short git SHA, or ``"unknown"``
      * ``date``     — ISO 8601 build date, or empty
      * ``source``   — ``"generated"``, ``"git"``, or ``"unknown"``
    """
    info = {
        "version": UNKNOWN_VERSION,
        "build":   UNKNOWN_VERSION,
        "commit":  "unknown",
        "date":    "",
        "source":  "unknown",
    }
    try:
        from agent import _version  # type: ignore[import-not-found]
    except Exception:
        _version = None  # type: ignore[assignment]

    if _version is not None:
        v = getattr(_version, "__version__", "") or ""
        if v.strip():
            info["version"] = v.strip()
            info["build"]   = getattr(_version, "__build__",  v).strip() or v
            info["commit"]  = getattr(_version, "__commit__", "unknown") or "unknown"
            info["date"]    = getattr(_version, "__date__",   "")        or ""
            info["source"]  = "generated"
            return info

    derived = derive_version_from_git()
    if derived:
        info["version"] = _public_version(derived)
        info["build"]   = derived
        # Try to lift the commit out of the build descriptor.
        m = re.search(r"\+(?:g)?([0-9a-f]{7,})", derived)
        info["commit"]  = m.group(1) if m else "unknown"
        info["source"]  = "git"
    return info


def _public_version(build_string: str) -> str:
    """Strip the local part (``+gabc1234.dirty``) from a build descriptor.

    Used to derive the user-facing ``version`` from the full ``build``.
    """
    if "+" in build_string:
        return build_string.split("+", 1)[0]
    return build_string


# ── SemVer parsing & Win32 VERSIONINFO conversion ──────────────────────────

def parse_semver(version: str) -> Optional[dict]:
    """Parse a SemVer 2.0.0 string into its components.

    Accepts the public version (no local part) — call ``_public_version()``
    first if you have a build descriptor.  Returns a dict with keys
    ``major`` ``minor`` ``patch`` ``prerelease`` ``build`` or ``None`` on
    failure.
    """
    m = _SEMVER_RE.match(version)
    if not m:
        return None
    g = m.groupdict()
    return {
        "major":      int(g["major"]),
        "minor":      int(g["minor"]),
        "patch":      int(g["patch"]),
        "prerelease": g.get("prerelease") or "",
        "build":      g.get("build")      or "",
    }


def semver_to_win32_tuple(version: str) -> Tuple[int, int, int, int]:
    """Convert a SemVer string to the (MAJOR, MINOR, PATCH, BUILD) 4-tuple
    that Win32 ``VS_FIXEDFILEINFO`` requires.

    Pre-release tags are ignored at the structural level (they only live in
    the ``ProductVersion`` string entry); ``BUILD`` is hard-coded to ``0``
    because SemVer's ``+build`` metadata is non-comparable per spec.
    """
    parsed = parse_semver(_public_version(version))
    if parsed is None:
        return (0, 0, 0, 0)
    return (parsed["major"], parsed["minor"], parsed["patch"], 0)


# ── Build-time helpers (called by build.py / build_installer.py / etc.) ────

def write_version_module(
    target_path: Path,
    version: str,
    build: Optional[str] = None,
    commit: str = "unknown",
    date: str = "",
) -> None:
    """Write the generated ``agent/_version.py`` consumed at runtime.

    Called by ``build.py``.  The build descriptor is the full string
    (including ``+gabc1234.dirty`` if applicable); ``version`` is the
    user-facing public part (no local).
    """
    target_path = Path(target_path)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    if build is None:
        build = version
    content = (
        '"""Generated by build.py — DO NOT EDIT BY HAND.\n'
        '\n'
        'This file is regenerated on every build and is gitignored.\n'
        'Source of truth: git tags. See VERSIONING.md.\n'
        '"""\n'
        f'__version__ = {version!r}\n'
        f'__build__   = {build!r}\n'
        f'__commit__  = {commit!r}\n'
        f'__date__    = {date!r}\n'
    )
    target_path.write_text(content, encoding="utf-8")


def render_pyinstaller_version_file(
    version: str,
    *,
    product_name: str = "Tlamatini",
    company_name: str = "XAIHT",
    file_description: str = "Tlamatini — Locally-deployed AI developer assistant",
    internal_name: str = "Tlamatini",
    original_filename: str = "Tlamatini.exe",
    legal_copyright: str = "GPL-3.0",
) -> str:
    """Return the contents of a PyInstaller ``--version-file`` for ``.exe``.

    The string follows the format PyInstaller's documentation specifies for
    Windows VERSIONINFO embedding.  Pass the result through
    ``Path.write_text()`` and hand the path to ``--version-file=...``.
    """
    filevers = semver_to_win32_tuple(version)
    public = _public_version(version)
    # StringFileInfo strings can be the full build descriptor — Windows
    # Explorer will show whichever you put in ProductVersion.
    return f"""# UTF-8
#
# Win32 VERSIONINFO resource generated by build.py.
# Do not edit by hand — regenerate via ``python build.py [--version X.Y.Z]``.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName',      u'{company_name}'),
            StringStruct(u'FileDescription',  u'{file_description}'),
            StringStruct(u'FileVersion',      u'{public}'),
            StringStruct(u'InternalName',     u'{internal_name}'),
            StringStruct(u'LegalCopyright',   u'{legal_copyright}'),
            StringStruct(u'OriginalFilename', u'{original_filename}'),
            StringStruct(u'ProductName',      u'{product_name}'),
            StringStruct(u'ProductVersion',   u'{version}'),
          ],
        ),
      ],
    ),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])]),
  ],
)
"""


__all__ = [
    "UNKNOWN_VERSION",
    "get_version",
    "get_version_info",
    "derive_version_from_git",
    "parse_semver",
    "semver_to_win32_tuple",
    "write_version_module",
    "render_pyinstaller_version_file",
]
