mode: send
whatsapp:
  phone_number_id: '1179153071946453'
  access_token: EAAd7WZAQU4HEBR91XAw3oHdPeY2m4yRZAvbZAQnKVxXPDDfUoGyov1hxdXUuk6Gn8yeCdwn9UHRBRcqskm0pKbW6I2jliYMMxlvnJd02m7LYpbXMHk1EXXTlUaoLdOUoZAH4R4WYUHCMGxZAiSCJgh9S4nZCaU9dBtWv0c2WbrxvDI7wQbbO7JOnOFEdWsi3Ocyqhbl2IZCOOVJySbJrbBQM0TwbFgNZCZAPXCbk81faPP2UWXPjAsZA4M8Cish2QNoeVh52tuF5hiy6ZAubbSkFoWoAQeRrpQRdmju4DvIUwZDZD
  graph_base: https://graph.facebook.com
  api_version: v20.0
  to: '+525559648601'
  verify_token: tlamatini
  webhook_host: 0.0.0.0
  webhook_port: 8086
  webhook_path: /wa-webhook
message: ''
contact_name: ''
template: hello_world
template_language: en_US
template_params: []
rx_max_seconds: 60
rx_from: ''
rx_match: ''
source_agents: []
target_agents: []
poll_interval: 2
recursion_limit: 1000
