# Generated by Django 5.2.4 on 2025-11-15 23:23

from django.db import migrations

def populate_initial_values(apps, schema_editor):
    """
    Populates the Prompts table with initial, default prompts.
    """
    Prompt = apps.get_model('agent', 'Prompt') 
    
    Prompt.objects.get_or_create(
        idPrompt=1,
        defaults={
            'promptName': 'prompt-1',
            'promptContent': 'List all of the files in the provided context, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=2,
        defaults={
            'promptName': 'prompt-2',
            'promptContent': 'Summarize in very detail the project\'s source code in the provided context, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=3,
        defaults={
            'promptName': 'prompt-3',
            'promptContent': 'What is te actual CPU usage, memory usage, and disk space?, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=4,
        defaults={
            'promptName': 'prompt-4',
            'promptContent': 'Search the file with name -----.--- in all allowed locations, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=5,
        defaults={
            'promptName': 'prompt-5',
            'promptContent': 'Find all files with the extension *.py in all allowed locations, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=6,
        defaults={
            'promptName': 'prompt-6',
            'promptContent': 'What is the current time now?, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=7,
        defaults={
            'promptName': 'prompt-7',
            'promptContent': 'Create an implementation of ----- in ----- to --- --- ---, provide all the neccesary files, and **REMEMBER to follow the rule "4) Code generation rule"**, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=8,
        defaults={
            'promptName': 'prompt-8',
            'promptContent': 'Explain what are the weak security issues you find on the source code in the provided context and how you may improve them focused in Cyber Security, **sort your findings from Critical severity to Low severity**, so, deeply analize the code, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=9,
        defaults={
            'promptName': 'prompt-9',
            'promptContent': 'Execute cat_art.py, located in the root of this application, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=10,
        defaults={
            'promptName': 'prompt-10',
            'promptContent': 'Run command ping x.x.x.x, and show its output as-is, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=11,
        defaults={
            'promptName': 'prompt-11',
            'promptContent': 'Run command netstat -an, and tell me if port 50051 is opened and whats its state, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=12,
        defaults={
            'promptName': 'prompt-12',
            'promptContent': 'View image \'MySxyFoto.jpg\' in all allowed locations, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=13,
        defaults={
            'promptName': 'prompt-13',
            'promptContent': 'List available directories, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=14,
        defaults={
            'promptName': 'prompt-14',
            'promptContent': 'Explain the purpose of \'-----.---\', from the provided context, please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=15,
        defaults={
            'promptName': 'prompt-15',
            'promptContent': 'Describe with Qwen the image \'----.---\' located in \'----\', please.'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=16,
        defaults={
            'promptName': 'prompt-16',
            'promptContent': 'Describe with Opus the image \'------.---\' located in \'------\' which is a mockup of a web page: **create a table listing all of the elements including menu entries, links, buttons, header, menu bar, side bars, etc. in a table with the format: element name, element type, element position (xpos%, ypos%), element size (width%, height%), element color, element text, element font-type, element font-size**, **STRICTLY NEVER ADD MORE ELEMENTS THAN THE ONES IN THE MOCKUP**, please.'
        }
    )
    
    Prompt.objects.get_or_create(
        idPrompt=17,
        defaults={
            'promptName': 'prompt-17',
            'promptContent': 'Describe with Qwen the image \'------.---\' located in \'------\' which is a mockup of a web page: **create a table listing all of the elements including menu entries, links, buttons, header, menu bar, side bars, etc. in a table with the format: element name, element type, element position (xpos%, ypos%), element size (width%, height%), element color, element text, element font-type, element font-size**, **STRICTLY NEVER ADD MORE ELEMENTS THAN THE ONES IN THE MOCKUP**, please.'
        }
    )
    
    Prompt.objects.get_or_create(
        idPrompt=18,
        defaults={
            'promptName': 'prompt-18',
            'promptContent': 'Create a web page using Bootstrap and jQuery **taking special attention to generate elements without overlapping each other**, with the exact same layout and elements that are described below:'
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=19,
        defaults={
            'promptName': 'prompt-19',
            'promptContent': 'Create a new version of the file "----.---" in order to include all the neccesary Java-Doc-style comments, **don´t modify the code at all**, and **REMEMBER to follow the rule "4) Code generation rule"**, it\'s original complete code is as follows: '
        }
    )

    Prompt.objects.get_or_create(
        idPrompt=20,
        defaults={
            'promptName': 'prompt-20',
            'promptContent': 'Decompile file "------\\------", please.'
        }
    )

    Mcp = apps.get_model('agent', 'Mcp') 
    
    Mcp.objects.get_or_create(
        idMcp=1,
        defaults={
            'mcpName': 'mcp-1',
            'mcpDescription': 'System-Metrics',
            'mcpContent': 'true'
        }
    )

    Mcp.objects.get_or_create(
        idMcp=2,
        defaults={
            'mcpName': 'mcp-2',
            'mcpDescription': 'Files-Search',
            'mcpContent': 'true'
        }
    )

    Tool = apps.get_model('agent', 'Tool') 
    
    Tool.objects.get_or_create(
        idTool=1,
        defaults={
            'toolName': 'tool-1',
            'toolDescription': 'Current-Time',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=2,
        defaults={
            'toolName': 'tool-2',
            'toolDescription': 'Execute-File',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=3,
        defaults={
            'toolName': 'tool-3',
            'toolDescription': 'Execute-Command',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=4,
        defaults={
            'toolName': 'tool-4',
            'toolDescription': 'View-Image',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=5,
        defaults={
            'toolName': 'tool-5',
            'toolDescription': 'Opus-Analyze-Image',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=6,
        defaults={
            'toolName': 'tool-6',
            'toolDescription': 'Monitor-Netstat',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=7,
        defaults={
            'toolName': 'tool-7',
            'toolDescription': 'Unzip-File',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=8,
        defaults={
            'toolName': 'tool-8',
            'toolDescription': 'Decompile-Java',
            'toolContent': 'true'
        }
    )

    Tool.objects.get_or_create(
        idTool=9,
        defaults={
            'toolName': 'tool-9',
            'toolDescription': 'Qwen-Analyze-Image',
            'toolContent': 'true'
        }
    )

    Agent = apps.get_model('agent', 'Agent') 
    
    Agent.objects.get_or_create(
        idAgent=1,
        defaults={
            'agentName': 'agent-1',
            'agentDescription': 'Monitor-Log',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=2,
        defaults={
            'agentName': 'agent-2',
            'agentDescription': 'Monitor-Netstat',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=3,
        defaults={
            'agentName': 'agent-3',
            'agentDescription': 'Raiser',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=4,
        defaults={
            'agentName': 'agent-4',
            'agentDescription': 'Ender',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=5,
        defaults={
            'agentName': 'agent-5',
            'agentDescription': 'Starter',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=6,
        defaults={
            'agentName': 'agent-6',
            'agentDescription': 'OR',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=7,
        defaults={
            'agentName': 'agent-7',
            'agentDescription': 'AND',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=8,
        defaults={
            'agentName': 'agent-8',
            'agentDescription': 'Emailer',
            'agentContent': 'true'
        }
    )


    Agent.objects.get_or_create(
        idAgent=9,
        defaults={
            'agentName': 'agent-9',
            'agentDescription': 'Croner',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=10,
        defaults={
            'agentName': 'agent-10',
            'agentDescription': 'Mover',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=11,
        defaults={
            'agentName': 'agent-11',
            'agentDescription': 'Sleeper',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=12,
        defaults={
            'agentName': 'agent-12',
            'agentDescription': 'Cleaner',
            'agentContent': 'true'
        }
    )

    Agent.objects.get_or_create(
        idAgent=13,
        defaults={
            'agentName': 'agent-13',
            'agentDescription': 'Whatsapper',
            'agentContent': 'true'
        }
    )

    Omission = apps.get_model('agent', 'Omission') 
    
    Omission.objects.get_or_create(
        idOmission=1,
        defaults={
            'omissionName': 'omission-1',
            'omissionContent': '*.jpg, *.bmp, *.svg, *.ico, *.tiff, *.png, *.webp, *.war, *.jar, *.class, *.exe, *.pdf, *.docx, *.xlsx, *.pptx, *.log, *.db, *.tlog, *.obj, *.res, *.idb, *.pdb, .gitignore, .vscode, .idea, .git, .gitmodules, .gitattributes, .gitignore, .gitkeep'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_values),
    ]
