source_agents: []
target_agents: []
telegram:
  api_id: <TELEGRAMER_API_ID goes here>
  api_hash: <TELEGRAMER_API_HASH goes here>
  chat_id: <TELEGRAMER_CHAT_ID goes here>
  message: Telegrammer parametrized and launched
poll_interval: 5
