source_agents: []
target_agents: []
telegram:
  api_id: 123456
  api_hash: adcb5adcbbad6676adc98112345678910
  chat_id: Angela-Bennet
  message: Telegrammer parametrized and launched
poll_interval: 5
