"""Regenerate/check the standalone agent catalog and its documentation inventory.

Run from any directory with the repository's Python environment:
    python scripts/update_flow_catalog.py [--check]
No application startup, agent execution, or network access is required.
"""
import argparse
import importlib
import json
import runpy
import sys
import types
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVICES = ROOT / "Tlamatini" / "agent" / "services"
# Load the pure service modules without executing services/__init__.py (Django).
package = types.ModuleType("_tlamatini_catalog_services")
package.__path__ = [str(SERVICES)]
sys.modules[package.__name__] = package
exporter = importlib.import_module(package.__name__ + ".flow_knowledge")


def render_inventory(catalog):
    agents = catalog["agents"]
    models = runpy.run_path(str(ROOT / "Tlamatini/agent/agents/model_settings.py"))
    lines = [
        "# Installed agent coverage", "",
        "Generated by `python scripts/update_flow_catalog.py`; verify with `--check`.", "",
        f"The catalog contains **{len(agents)} installed agent types**. Every row has a current configuration schema, "
        "canonical name, aliases, connection slots, lifecycle flags, and declared structured output fields. "
        "Field types are inferred from templates; they are not a complete semantic validator. "
        "No template values or credentials are exported. GUI-Manager remains a design and is excluded.", "",
        "FlowCreator selects from the entire catalog, then receives detailed reference and schema for the selected types. "
        "Deployment refreshes the catalog for FlowCreator, FlowHypervisor, and Parametrizer. "
        "This coverage demonstrates discoverability and contract coverage, not successful live execution of every possible workflow.", "",
        f"Config → Models exposes **{len(models['FIELDS'])} model/engine/voice settings** for "
        f"**{len(models['AGENTS'])} model-backed agents**. Missing registered fields and quoted `\"@config\"` "
        "inherit global choices; literal canvas/standalone values remain overrides. "
        "See [model configuration](model_configuration.md) for all keys, defaults and launch-path precedence, "
        "and [dated source/frozen verification](model-configuration-verification.md) for runtime evidence. "
        "The offline `check_agent_runtimes` gate prepares every template, executes model loaders, refreshes "
        "helpers/catalogs and runs File-Creator; it does not exercise every provider or hardware action.", "",
        "| Agent | Config keys | Structured fields | Output slots | Lifecycle |",
        "|---|---:|---:|---|---|",
    ]
    for name, spec in agents.items():
        slots = ", ".join(f"{k}: `{v}`" for k, v in spec["output_slots"].items())
        flags = ", ".join(k for k in ("singleton", "no_input", "no_output", "long_running", "never_starts_targets") if spec[k]) or "ordinary"
        lines.append(f"| {spec['display_name']} (`{name}`) | {len(spec['config_schema'])} | {len(spec['output_fields'])} | {slots} | {flags} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = exporter.build_catalog()
    outputs = {
        ROOT / "Tlamatini/agent/agents/flowcreator/flow_catalog.json": json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
        ROOT / "docs/agent-coverage.md": render_inventory(catalog),
    }
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"Stale generated file: {path}; run without --check")
        else:
            path.write_text(text, encoding="utf-8")
    print(f"{'Verified' if args.check else 'Generated'} coverage for {len(catalog['agents'])} agent types")


if __name__ == "__main__":
    main()
