# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Crafted with heart by  Angela   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
"""
Django settings for tlamatini project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
import time

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Tlamatini Temp policy ────────────────────────────────────────────────────
# Pin ALL temporary files to ``<application-root>/Temp`` so nothing ever leaks
# to ``C:\Temp`` / ``%TEMP%``.  manage.py already does this before Django on the
# normal launch paths; this repeats it (idempotently) in settings so a DIRECT
# ``daphne tlamatini.asgi:application`` / ``uvicorn`` launch that bypasses
# manage.py is still covered.  Self-contained, fail-open; resolution matches
# manage.py::_enforce_app_temp_dir and agent/path_guard.py::_get_application_root
# (frozen → exe dir; source → repo root = the dir above this Django project).
def _pin_temp_directory():
    try:
        if getattr(sys, 'frozen', False):
            _temp_base = Path(sys.executable).resolve().parent
        else:
            _temp_base = BASE_DIR.parent
        _temp_root = _temp_base / 'Temp'
        _temp_root.mkdir(parents=True, exist_ok=True)
        _temp_root_str = str(_temp_root)
        for _var in ('TMP', 'TEMP', 'TMPDIR'):
            os.environ[_var] = _temp_root_str
        os.environ['TLAMATINI_TEMP'] = _temp_root_str
        import tempfile
        tempfile.tempdir = _temp_root_str
        # Templates: default parent for firmware/engine agent scaffold projects.
        _templates_root = _temp_base / 'Templates'
        _templates_root.mkdir(parents=True, exist_ok=True)
        os.environ['TLAMATINI_TEMPLATES'] = str(_templates_root)
        # Frozen: pool agents run on the CARRIED Python (<install>/python); force them
        # to ignore any stray per-user site-packages (%APPDATA%/Python) so they run
        # COMPLETELY on the carried interpreter's own libs. Inherited by every child.
        # Per-user lib dirs that use PYTHONPATH (e.g. ESPHomer's esphome-lib) are NOT
        # affected. Source mode is left alone (dev relies on its environment).
        if getattr(sys, 'frozen', False):
            os.environ['PYTHONNOUSERSITE'] = '1'
    except Exception:
        pass


_pin_temp_directory()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$f=fy&i80tqgzy%#^x@^am%)duwk7qq5_*807l)mtrsj$$7wk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agent',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add dev-only HTML no-cache to ensure pages revalidate while static files are hashed
if DEBUG:
    MIDDLEWARE.append('tlamatini.middleware.NoCacheHTMLMiddleware')

ROOT_URLCONF = 'tlamatini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tlamatini.context_processors.static_version',
                'tlamatini.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'tlamatini.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use an absolute URL path for static files
STATIC_URL = '/static/'

# Default location where collectstatic will place files during development
STATIC_ROOT = BASE_DIR / "staticfiles"

# When running as a PyInstaller-frozen app, static files live alongside the executable
if getattr(sys, 'frozen', False):
    frozen_base_dir = Path(getattr(sys, '_MEIPASS', Path(sys.executable).parent))
    STATIC_ROOT = frozen_base_dir / "staticfiles"

# Version stamp for cache-busting of static assets in templates
# Override via env var STATIC_VERSION when deploying
STATIC_VERSION = os.environ.get('STATIC_VERSION') or str(int(time.time()))

# WhiteNoise configuration: dev vs prod
if DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    WHITENOISE_AUTOREFRESH = True
    WHITENOISE_MAX_AGE = 0
else:
    # Use hashed filenames and long cache in production
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_AUTOREFRESH = False
    # 1 year; files are immutable due to hashing
    WHITENOISE_MAX_AGE = 31536000

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# myproject/settings.py
ASGI_APPLICATION = 'tlamatini.asgi.application'

LOGIN_URL = 'home'

# Channel Layer configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Logging configuration – ensures that agent.chat_agent_runtime, agent.tools,
# and agent.mcp_agent INFO-level messages are visible in the console.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "suppress_http_get_200": {
            "()": "tlamatini.logging_filters.SuppressHttpGet200",
        },
    },
    "formatters": {
        "chat_runtime": {
            "format": "%(asctime)s [%(name)s] %(levelname)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "chat_runtime",
        },
    },
    "loggers": {
        "agent.chat_agent_runtime": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.tools": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.mcp_agent": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.global_execution_planner": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.capability_registry": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.channels.server": {
            "filters": ["suppress_http_get_200"],
        },
    },
}